---
title: 'Learning Lab 1 Essential Readings'
author: "Dr. Joshua Rosenberg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
editor_options:
  markdown:
    wrap: 72
bibliography: lit/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required

Rosenberg, J. M., Reid, J. W., Dyer, E. B., Koehler, M. J., Fischer, C., & McKenna, T. J. (2020). Idle chatter or compelling conversation? The potential of the social media‐based# NGSSchat network for supporting science education reform efforts. Journal of Research in Science Teaching, 57(9), 1322-1355.

*This paper presents the qualitative coding of a large number of tweets to the #NGSSchat (organized around threads). As you read this work, question what opportunities and challenges might result from scaling up the qualitative codes of transactional and substantive conversations.*

> The Next Generation Science Standards (NGSS) chat (#NGSSchat) is a social media-based professional network used to discuss topics related to the NGSS in the United States. While successful reforms involve and coordinate the work of multiple stakeholders, recent research points out a striking lack of coordination between the individuals working in different educational roles—to the detriment of intended changes in the system. In this study, we analyzed more than 7,000 posts from individuals participating in #NGSSchat on Twitter (n = 247) during 2 years of 1-hr synchronous discussions. We studied the depth and types of conversations that took place, the extent to which the involvement of teachers, administrators, researchers, and organizations was balanced, and what explains participation in the network over time. Using a mixed-methods approach involving social network analysis, we found that conversations were primarily transactional, or social, and substantive, or providing opportunities for sense-making about the standards or for participants to transform their practice and that individuals from diverse roles participated, with teachers comprising the plurality of those involved. Additionally, researchers, administrators, and teachers were the most active in the network, with no differences in both initiating, or sending, and being the recipients of, or receiving, replies as a part of conversations. Finally, we found that being a teacher or administrator, as well as receiving replies from individuals who were important in the network, were positively related to sustained involvement in the network in the following year. We discuss how #NGSSchat—as a social media-based professional network—demonstrates similar features in other effective networks, and how social media-based networks invite new visions for how to implement ambitious, large-scale changes in science education.

Maestrales, S., Zhai, X., Touitou, I., Baker, Q., Schneider, B., & Krajcik, J. (2021). Using machine learning to score multi-dimensional assessments of chemistry and physics. Journal of Science Education and Technology, 30(2), 239-254.

*This paper presents a great example of how coded data and a coding frame can be "scaled up", here for assessment-related purposes. Read through this paper, noting how the authors fit and interpreted the output of their supervised machine learning classification models. Were they successful in your view?*

> In response to the call for promoting three-dimensional science learning (NRC, 2012), researchers argue for developing assessment items that go beyond rote memorization tasks to ones that require deeper understanding and the use of reasoning that can improve science literacy. Such assessment items are usually performance-based constructed responses and need technology involvement to ease the burden of scoring placed on teachers. This study responds to this call by examining the use and accuracy of a machine learning text analysis protocol as an alternative to human scoring of constructed response items. The items we employed represent multiple dimensions of science learning as articulated in the 2012 NRC report. Using a sample of over 26,000 constructed responses taken by 6700 students in chemistry and physics, we trained human raters and compiled a robust training set to develop machine algorithmic models and cross-validate the machine scores. Results show that human raters yielded good (Cohen’s k=.40–.75) to excellent (Cohen’s k>.75) interrater reliability on the assessment items with varied numbers of dimensions. A comparison reveals that the machine scoring algorithms achieved comparable scoring accuracy to human raters on these same items. Results also show that responses with formal vocabulary (e.g., velocity) were likely to yield lower machine-human agreements, which may be associated with the fact that fewer students employed formal phrases compared with the informal alternatives.

## Optional

van Bommel, J., Randahl, A. C., Liljekvist, Y., & Ruthven, K. (2020). Tracing teachers’ transformation of knowledge in social media. Teaching and Teacher Education, 87, 102958. https://www.sciencedirect.com/science/article/pii/S0742051X19300629

> Social media represent an increasingly important vehicle for informal professional development amongst teachers, and provide an illuminating means of tracing their collective knowledge building. The study reported here examines six large Facebook groups, created by and for teachers in Sweden, to exchange information about the teaching of mathematics and Swedish. Analysis establishes that professional knowledge was made available in 86% of discussion threads, most commonly relating to Shulman’s categories of Knowledge of Learners, Curricular Knowledge, and Pedagogical Content Knowledge. Participants acknowledged opportunities for professional learning in 88% of such threads, and showed new understanding in 11%, particularly in longer threads.

