---
title: 'Learning Lab 2 Essential Readings'
author: "Dr. Joshua Rosenberg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
editor_options:
  markdown:
    wrap: 72
bibliography: lit/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Salmeron-Majadas, S., Baker, R. S., Santos, O. C., & Boticario, J. G. (2018). A machine learning approach to leverage individual keyboard and mouse interaction behavior from multiple users in real-world learning scenarios. IEEE Access, 6, 39154-39179.

> There is strong evidence that emotions influence the learning process. For this reason, we explore the relevance of individual and general mouse and keyboard interaction patterns in real-world settings while learners perform free text tasks. To this end, we have modeled users' mouse movements and keystroke dynamics with data mining techniques, building on previous related research and extending it in terms of some critical modeling issues that may have an impact on detection results. Inspired by practice in affective computing where physiological sensors are used, we argue for the creation of an interaction baseline model, as a reference point in the way how learners interact with the keyboard and mouse. To make the proposed affective model feasible, we have adopted a simplified 2-D self-labeling approach for labeling the users' affective state. Our approach to affect detection improves results when there is a small amount of data instances available and does not require additional affect-oriented tasks from the learners. Specifically, learners are only asked to self-reflect their emotional state after finishing the tasks and immediately selecting two values in the affect scale. The approach we have followed aims to distill two types of interaction patterns: 1) within-subject patterns (from a single participant) and 2) between-subject patterns (across all participants). Doing this, we aim to combine both the approaches as modeling factors, thus taking advantage of individual and general interaction patterns to predict affect.

Li, Q., Baker, R., & Warschauer, M. (2020). Using clickstream data to measure, understand, and support self-regulated learning in online courses. The Internet and Higher Education, 45, 100727. https://github.com/laser-institute/essential-readings/blob/main/machine-learning/ml-lab-2/li-et-al-2020-ihe.pdf

> The ability to regulate one's own learning is essential for success in online courses. Recent efforts have used clickstream data to create timely, fine-grained, and comprehensive measures of self-regulated learning (SRL) in online courses in an attempt to shed light on the process of SRL and to improve the identification of students who lack SRL skills and are at risk of low achievement. However, key questions remain: to what extent do these clickstream measures correspond to traditional self-reported measures about specific SRL constructs? Do these clickstream measures provide more information than existing self-reported measures in predicting course performance? This study used the clickstream data collected from a learning management system to measure two aspects of SRL: time management and effort regulation. We found that the clickstream measures were significantly associated with students' self-reported time management and effort regulation after the course. In addition, these clickstream measures significantly improved predictions of students' performance in the current and subsequent courses over predictions based on self-reported measures alone. These results provide evidence for the validity of the clickstream measures and guide the use of clickstream data to understand the process of SRL and identify students who might not be well served by taking classes online.

Gobert, J. D., Sao Pedro, M., Raziuddin, J., & Baker, R. S. (2013). From log files to assessment metrics: Measuring students' science inquiry skills using educational data mining. Journal of the Learning Sciences, 22(4), 521-563. https://github.com/laser-institute/essential-readings/blob/main/machine-learning/ml-lab-3/gobert-et-al-2013-jls.pdf

> We present a method for assessing science inquiry performance, specifically for the inquiry skill of designing and conducting experiments, using educational data mining on students' log data from online microworlds in the Inq-ITS system (Inquiry Intelligent Tutoring System; www.inq-its.org). In our approach, we use a 2-step process: First we use text replay tagging, a type of rapid protocol analysis in which categories are developed and, in turn, used to hand-score students' log data. In the second step, educational data mining is conducted using a combination of the text replay data and machine-distilled features of student interactions in order to produce an automated means of assessing the inquiry skill in question; this is referred to as a detector. Once this detector is appropriately validated, it can be applied to students' log files for auto-assessment and, in the future, to drive scaffolding in real time. Furthermore, we present evidence that this detector developed in 1 scientific domain, phase change, can be used—with no modification or retraining—to effectively detect science inquiry skill in another scientific domain, density.

Bosch, N. (2021). AutoML Feature Engineering for Student Modeling Yields High Accuracy, but Limited Interpretability. Journal of Educational Data Mining, 13(2), 55-79. https://github.com/laser-institute/essential-readings/blob/main/machine-learning/ml-lab-3/bosch-et-al-2021-jedm.pdf

> Automatic machine learning (AutoML) methods automate the time-consuming, feature-engineering process so that researchers produce accurate student models more quickly and easily. In this paper, we compare two AutoML feature engineering methods in the context of the National Assessment of Educational Progress (NAEP) data mining competition. The methods we compare, Featuretools and TSFRESH (Time Series FeatuRe Extraction on basis of Scalable Hypothesis tests), have rarely been applied in the context of student interaction log data. Thus, we address research questions regarding the accuracy of models built with AutoML features, how AutoML feature types compare to each other and to expert-engineered features, and how interpretable the features are. Additionally, we developed a novel feature selection method that addresses problems applying AutoML feature engineering in this context, where there were many heterogeneous features (over 4,000) and relatively few students. Our entry to the NAEP competition placed 3rd overall on the final held-out dataset and 1st on the public leaderboard, with a final Cohen's kappa = .212 and area under the receiver operating characteristic curve (AUC) = .665 when predicting whether students would manage their time effectively on a math assessment. We found that TSFRESH features were significantly more effective than either Featuretools features or expert-engineered features in this context; however, they were also among the most difficult features to interpret based on a survey of six experts' judgments. Finally, we discuss the tradeoffs between effort and interpretability that arise in AutoML-based student modeling.

Rodriguez, F., Lee, H. R., Rutherford, T., Fischer, C., Potma, E., & Warschauer, M. (2021, April). Using clickstream data mining techniques to understand and support first-generation college students in an online chemistry course. In LAK21: 11th International Learning Analytics and Knowledge Conference (pp. 313-322). https://github.com/laser-institute/essential-readings/blob/main/machine-learning/ml-lab-2/rodriguez-et-al-2021-lak.pdf

> Although online courses can provide students with a high-quality and flexible learning experience, one of the caveats is that they require high levels of self-regulation. This added hurdle may have negative consequences for first-generation college students. In order to better understand and support students’ self-regulated learning, we examined a fully online Chemistry course with high enrollment (N = 312) and a high percentage of first-generation college students (65.70%). Using students’ lecture video clickstream data, we created two indicators of self-regulated learning: lecture video completion and time management. Performing a k-means clustering on these indicators uncovered four distinct self-regulated learning patterns: (1) Early Planning, (2) Planning, (3) Procrastination, and (4) Low Engagement. Early Planning behaviors were especially important for course success—they consistently predicted higher final course grades, even after controlling for important demographic variables. Interestingly, first-generation college students classified as Early Planners achieved at similar levels as their non-first-generation peers, but first-generation students in the Low Engagement group had the lowest average grades among students. Overall, our results show that self-regulation may be an important skill for determining first-generation students’ STEM achievement, and targeting these skills may serve as a useful way to support their specific learning needs.