---
title: 'Learning Lab 4 Essential Readings'
author: "Dr. Joshua Rosenberg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
editor_options:
  markdown:
    wrap: 72
bibliography: lit/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Commeford, K., Brewe, E., & Traxler, A. (2022). Characterizing active learning environments in physics using latent profile analysis. Physical Review Physics Education Research, 18(1), 010113. https://github.com/laser-institute/essential-readings/blob/main/machine-learning/ml-lab-4/commeford-et-al-2022-per.pdf

> The vast majority of research involving active learning pedagogies uses passive lecture methods as a baseline. We propose to move beyond such comparisons to understand the mechanisms that make different active learning styles unique. Here, we use COPUS observations to record student and instructor activities in six known styles of active learning in physics, and use latent profile analysis to classify these observations. Latent profile analysis using two profiles successfully groups COPUS profiles into interactive lecturelike and other. Five latent profiles successfully sorts observations into interactive lecturelike, Modeling Instruction, ISLE labs, context-rich problems labs, and recitationlike or discussionlike. This analysis serves as a proof of concept, and suggests instructional differences across pedagogies that can be further investigated using this method.

Pastor, D. A., Barron, K. E., Miller, B. J., & Davis, S. L. (2007). A latent profile analysis of college students’ achievement goal orientation. Contemporary educational psychology, 32(1), 8-47. https://github.com/laser-institute/essential-readings/blob/main/machine-learning/ml-lab-4/pastor-et-al-2007-cep.pdf

> Achievement goal research has grown increasingly complex with the number of proposed goal orientations that motivate students. As the number of proposed goal constructs proliferates, a variety of data analytic challenges have emerged, such as profiling students on different types of goal pursuit as well as evaluating the relationships of multiple goal pursuit with different educational outcomes. The purpose of the current article is to showcase the advantages of using latent profile analysis (LPA) over other traditional techniques (such as multiple regression and cluster analysis) when analyzing multidimensional data like achievement goals. Specifically, we review the advantages of LPA over traditional person- and variable-centered analyses and then provide a critical look at three different conceptualizations of goal orientation (2-, 3-, and 4-factor) using LPA.

Nelson, L. K. (2020). Computational grounded theory: A methodological framework. *Sociological Methods & Research, 49*(1), 3-42.

> This article proposes a three-step methodological framework called com- putational grounded theory, which combines expert human knowledge and hermeneutic skills with the processing power and pattern recognition of computers, producing a more methodologically rigorous but interpretive approach to content analysis. The first, pattern detection step, involves inductive computational exploration of text, using techniques such as unsupervised machine learning and word scores to help researchers to see novel patterns in their data. The second, pattern refinement step, returns to an interpretive engagement with the data through qualitative deep reading or further exploration of the data. The third, pattern confirmation step, assesses the inductively identified patterns using further computational and natural language processing techniques. The result is an efficient, rigorous, and fully reproducible computational grounded theory. This framework can be applied to any qualitative text as data, including transcribed speeches, interviews, open-ended survey data, or ethnographic field notes, and can address many potential research questions.

San Pedro, M. O., Ocumpaugh, J., Baker, R. S., & Heffernan, N. T. (2014, July). Predicting STEM and Non-STEM College Major Enrollment from Middle School Interaction with Mathematics Educational Software. In EDM (pp. 276-279).

> The worldwide increase in demand for qualified workers in science, technology, engineering, and mathematics (STEM) fields has resulted in a greater focus on preparing students to enroll in postsecondary STEM programs. The processes that lead students to become interested in and equip them for STEM careers begin years earlier. Previous research indicates that family background, financial resources, and prior family academic achievement can be used to predict whether a student will enroll in a STEM major. In this paper, we consider another class of factors that may be predictive while being more actionable. In this paper, we use predictive analytics, based on previously-validated automated detectors of student learning and engagement, to predict which students will choose a STEM major. With data from 363 college students who used ASSISTments during their regular middle school math classes, we develop a model that can successfully distinguish 66% of the time if a student will choose a STEM major or a non-STEM major when they enter college. In doing so, we offer steps towards providing educators with more actionable information on the STEM trajectories of individual students